import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link'
import { useRouter } from "next/router";
import useTranslation from "next-translate/useTranslation";

import setLanguage from "next-translate/setLanguage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { t } = useTranslation();
  const router = useRouter();


  const chooseLanguage = async ( countryCode, lng ) => { 
    
    //   closeModal()
    //   const newLocale = `${countryCode}-${lng}`;
    //   await setLanguage(newLocale);
    
    //   const currentPath = router.asPath;
    //   const translatedPath = UsePathTranslation(currentPath, newLocale);
      
    //   // Construct the new URL with the new locale and the translated path
    //   const newUrl = `/${newLocale}${translatedPath}`; 
    //   router.replace(newUrl);
    
    //  fetchStyle();
    //  fetchAll(countryCode);
  
  
  
  
    await setLanguage(`${countryCode}-${lng}`);

    const newUrl =`/${countryCode}-${lng}${router.asPath}`;
    router.replace(newUrl);
  
    
    };

  console.log(router.locale,"cdskdc")


const countries =
[
  {
    "id": 3011,
    "country": "german",
    "language": "german",
    "image": "/spain.svg",
    "countryCode": "ch",
    "lng": "en",
    "set": "ch-en"
  },

  {
    "id": 301,
    "country": "german",
    "language": "german",
    "image": "/spain.svg",
    "countryCode": "de",
    "lng": "de",
    "set": "de-de"
  },
  {
    "id": 30,
    "country": "España",
    "language": "Español",
    "image": "/spain.svg",
    "countryCode": "es",
    "lng": "es",
    "set": "es-es"
  },
  
]






  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        


<div style={{"display":"flex" ,"justifyContent":"space-between" ,'gap':"11px"}}>

<Link href={`/${router.locale}/${t('common:routes.klarna')}`}>
      Klarna
    </Link>

    <Link href={`/${router.locale}/${t('common:routes.for-tattoo-artists')}`}>
    Artist
    </Link>

<Link href="/for-tattoo-artists"></Link>











</div>




<ul>
                  {countries.map((el) => {
                    return (
                      <li key={el.id}>
                        <button
                          className={
                            router.locale === el.set
                              ? "activeCountry"
                              : "inActivecountry"
                              
                          }
                          disabled={router.locale === el.set}
                          onClick={() => chooseLanguage(el.countryCode, el.lng  ,el.country)}
                        >
                          <Image
                            alt={`${el.country}${"-"}${el.language}`}
                            src={el.image}
                            width={32}
                            height={32}
                          />
                          <span>
                            <h4>{el.country}</h4>
                            <p>{el.language}</p>
                          </span>
                          {/* <Image
                            width={24}
                            height={25}
                            src="/icon_language_link.svg"
                            alt=""
                            className="icon_language_link"
                          /> */}
                        </button>
                      </li>
                    );
                  })}
                </ul>
   


      </main>
    </>
  );
}
